### ISSUE TITLE
Could not create a native instance

### ISSUE THREAD

**Issue by ceichin** [jzeferino/Xamarin.iOS.DGActivityIndicatorView#1]
Hi, I'm getting the following error in execution time on simulator:

```
Could not create an native instance of the type 'Xamarin.iOS.DGActivityIndicatorViewBinding.DGActivityIndicatorView': the native class hasn't been loaded.
It is possible to ignore this condition by setting ObjCRuntime.Class.ThrowOnInitFailure to false.
```

Thanks! :)

**Comment by jzeferino** [comment]
I've tested it now on a new project, in simulator in Release and in Debug, and it worked well.
Can you tell me the Xamarin / Ios versions you have? If you want to share the source code with me please feel free to do it.

**Comment by ceichin** [comment]
I changed the supported architecture from i386 to x86_64 and it worked perfectly! Thanks, awesome binding.

**Comment by jzeferino** [comment]
@ceichin were did you changed the supported architecture?

**Comment by ceichin** [comment]
Sorry for the late response. In Xamarin Studio you do right click on the iOS project -> Options -> Tab iOS Build -> Set the Supported Architecture (my options are i386, x86_64 or both). I suppose the .a file of the binding does not support the i386 architecture, but I don't know if that is really needed, I just changed that and everything worked.

**Comment by jzeferino** [comment]
The fat library (.a) was created targeting `i386`, `armv7` and `arm64`. You should't have problems using it. I created a new Xamarin.iOS project pulled the nuget and it worked well in device and emulator.

**Comment by ceichin** [comment]
Weird.. I created a new iOS single view project, installed the nuget and just added the spinner to the ViewControllers's View. By default it works perfectly, but when changing to i386 it throws the error. Maybe I need to do something more when changing to i386... Idk, but its working for me now using x86_64 :) 

Just to give you more info, it was tested on the iPhone SE simulator with iOS10.3, XCode 8.3.

**Comment by jzeferino** [comment]
Why did you need to change the target to i386? I don't need to do that to run on emulators.

**Comment by ceichin** [comment]
I don't remember, it's an old project already.

**Comment by jzeferino** [comment]
Ok. Im gonna close it. Thank you.
