### ISSUE TITLE
Linker issue: was built for newer iOS version (10.1) than being linked (9.0)

### ISSUE THREAD

**Issue by cfl777** [jzeferino/Xamarin.iOS.DGActivityIndicatorView#5]
Massive linker issues with this project started when I uninstalled firebase packages from my project, have no idea how that could have triggered issues with this lib.

You do support to 8.0, not sure why it needs 10.1, according to the issues below:

error MT5209 : Native linking error : warning: object file (/...iOS/obj/iPhoneSimulator/Debug/mtouch-cache/libDGActivityIndicatorView.a(DGActivityIndicatorBallClipRotateAnimation.o)) was built for newer iOS version (10.1) than being linked (9.0)
error MT5209 : Native linking error : warning: object file (.../obj/iPhoneSimulator/Debug/mtouch-cache/libDGActivityIndicatorView.a(DGActivityIndicatorBallClipRotatePulseAnimation.o)) was built for newer iOS version (10.1) than being linked (9.0)
error MT5209 : Native linking error : warning: object file (.../obj/iPhoneSimulator/Debug/mtouch-cache/libDGActivityIndicatorView.a(DGActivityIndicatorBallGridBeatAnimation.o)) was built for newer iOS version (10.1) than being linked (9.0)
error MT5209 : Native linking error : warning: object file (.../obj/iPhoneSimulator/Debug/mtouch-cache/libDGActivityIndicatorView.a(DGActivityIndicatorBallPulseAnimation.o)) was built for newer iOS version (10.1) than being linked (9.0)
error MT5209 : Native linking error : warning: object file (.../obj/iPhoneSimulator/Debug/mtouch-cache/libDGActivityIndicatorView.a(DGActivityIndicatorBallRotateAnimation.o)) was built for newer iOS version (10.1) than being linked (9.0)
error MT5209 : Native linking error : warning: object file (.../obj/iPhoneSimulator/Debug/mtouch-cache/libDGActivityIndicatorView.a(DGActivityIndicatorBallScaleAnimation.o)) was built for newer iOS version (10.1) than being linked (9.0)
error MT5209 : Native linking error : warning: object file (.../iPhoneSimulator/Debug/mtouch-cache/libDGActivityIndicatorView.a(DGActivityIndicatorBallSpinFadeLoader.o)) was built for newer iOS version (10.1) than being linked (9.0)
error MT5209 : Native linking error : warning: object file (/.../obj/iPhoneSimulator/Debug/mtouch-cache/libDGActivityIndicatorView.a(DGActivityIndicatorBallTrianglePathAnimation.o)) was built for newer iOS version (10.1) than being linked (9.0)
error MT5209 : Native linking error : warning: object file (.../obj/iPhoneSimulator/Debug/mtouch-cache/libDGActivityIndicatorView.a(DGActivityIndicatorBallZigZagAnimation.o)) was built for newer iOS version (10.1) than being linked (9.0)
error MT5209 : Native linking error : warning: object file (.../obj/iPhoneSimulator/Debug/mtouch-cache/libDGActivityIndicatorView.a(DGActivityIndicatorBallZigZagDeflectAnimation.o)) was built for newer iOS version (10.1) than being linked (9.0)
error MT5209 : Native linking error : warning: object file (.../obj/iPhoneSimulator/Debug/mtouch-cache/libDGActivityIndicatorView.a(DGActivityIndicatorFiveDotsAnimation.o)) was built for newer iOS version (10.1) than being linked (9.0)
error MT5209 : Native linking error : warning: object file (.../obj/iPhoneSimulator/Debug/mtouch-cache/libDGActivityIndicatorView.a(DGActivityIndicatorBallScaleMultipleAnimation.o)) was built for newer iOS version (10.1) than being linked (9.0)
error MT5209 : Native linking error : warning: object file (/.../obj/iPhoneSimulator/Debug/mtouch-cache/libDGActivityIndicatorView.a(DGActivityIndicatorLineScaleAnimation.o)) was built for newer iOS version (10.1) than being linked (9.0)
error MT5209 : Native linking error : warning: object file (.../obj/iPhoneSimulator/Debug/mtouch-cache/libDGActivityIndicatorView.a(DGActivityIndicatorLineScalePartyAnimation.o)) was built for newer iOS version (10.1) than being linked (9.0)
error MT5209 : Native linking error : warning: object file (.../obj/iPhoneSimulator/Debug/mtouch-cache/libDGActivityIndicatorView.a(DGActivityIndicatorNineDotsAnimation.o)) was built for newer iOS version (10.1) than being linked (9.0)
error MT5209 : Native linking error : warning: object file (.../obj/iPhoneSimulator/Debug/mtouch-cache/libDGActivityIndicatorView.a(DGActivityIndicatorDoubleBounceAnimation.o)) was built for newer iOS version (10.1) than being linked (9.0)
error MT5209 : Native linking error : warning: object file (.../obj/iPhoneSimulator/Debug/mtouch-cache/libDGActivityIndicatorView.a(DGActivityIndicatorRotatingSandglassAnimation.o)) was built for newer iOS version (10.1) than being linked (9.0)
error MT5209 : Native linking error : warning: object file (.../obj/iPhoneSimulator/Debug/mtouch-cache/libDGActivityIndicatorView.a(DGActivityIndicatorThreeDotsAnimation.o)) was built for newer iOS version (10.1) than being linked (9.0)
error MT5209 : Native linking error : warning: object file (.../obj/iPhoneSimulator/Debug/mtouch-cache/libDGActivityIndicatorView.a(DGActivityIndicatorTriangleSkewSpinAnimation.o)) was built for newer iOS version (10.1) than being linked (9.0)
error MT5209 : Native linking error : warning: object file (.../obj/iPhoneSimulator/Debug/mtouch-cache/libDGActivityIndicatorView.a(DGActivityIndicatorTripleRingsAnimation.o)) was built for newer iOS version (10.1) than being linked (9.0)
error MT5209 : Native linking error : warning: object file (.../obj/iPhoneSimulator/Debug/mtouch-cache/libDGActivityIndicatorView.a(DGActivityIndicatorView-C0A72BD5D2D8F190.o)) was built for newer iOS version (10.1) than being linked (9.0)
error MT5209 : Native linking error : warning: object file (.../obj/iPhoneSimulator/Debug/mtouch-cache/libDGActivityIndicatorView.a(DGActivityIndicatorBallPulseSyncAnimation.o)) was built for newer iOS version (10.1) than being linked (9.0)
error MT5209 : Native linking error : warning: object file (.../obj/iPhoneSimulator/Debug/mtouch-cache/libDGActivityIndicatorView.a(DGActivityIndicatorLineScalePulseOutAnimation.o)) was built for newer iOS version (10.1) than being linked (9.0)
error MT5209 : Native linking error : warning: object file (.../obj/iPhoneSimulator/Debug/mtouch-cache/libDGActivityIndicatorView.a(DGActivityIndicatorTriplePulseAnimation.o)) was built for newer iOS version (10.1) than being linked (9.0)
error MT5209 : Native linking error : warning: object file (.../obj/iPhoneSimulator/Debug/mtouch-cache/libDGActivityIndicatorView.a(DGActivityIndicatorRotatingSquaresAnimation.o)) was built for newer iOS version (10.1) than being linked (9.0)
error MT5209 : Native linking error : warning: object file (.../obj/iPhoneSimulator/Debug/mtouch-cache/libDGActivityIndicatorView.a(DGActivityIndicatorRotatingTrigonAnimation.o)) was built for newer iOS version (10.1) than being linked (9.0)
error MT5209 : Native linking error : warning: object file (.../obj/iPhoneSimulator/Debug/mtouch-cache/libDGActivityIndicatorView.a(DGActivityIndicatorTwoDotsAnimation.o)) was built for newer iOS version (10.1) than being linked (9.0)
error MT5209 : Native linking error : warning: object file (.../obj/iPhoneSimulator/Debug/mtouch-cache/libDGActivityIndicatorView.a(DGActivityIndicatorBallScaleRippleAnimation.o)) was built for newer iOS version (10.1) than being linked (9.0)
error MT5209 : Native linking error : warning: object file (.../obj/iPhoneSimulator/Debug/mtouch-cache/libDGActivityIndicatorView.a(DGActivityIndicatorBallScaleRippleMultipleAnimation.o)) was built for newer iOS version (10.1) than being linked (9.0)
error MT5209 : Native linking error : warning: object file (.../obj/iPhoneSimulator/Debug/mtouch-cache/libDGActivityIndicatorView.a(DGActivityIndicatorCookieTerminatorAnimation.o)) was built for newer iOS version (10.1) than being linked (9.0)
error MT5209 : Native linking error : warning: object file (.../obj/iPhoneSimulator/Debug/mtouch-cache/libDGActivityIndicatorView.a(DGActivityIndicatorBallBeatAnimation.o)) was built for newer iOS version (10.1) than being linked (9.0)
error MT5209 : Native linking error : warning: object file (/.../obj/iPhoneSimulator/Debug/mtouch-cache/libDGActivityIndicatorView.a(DGActivityIndicatorLineScalePulseOutRapidAnimation.o)) was built for newer iOS version (10.1) than being linked (9.0)
error MT5209 : Native linking error : warning: object file (.../obj/iPhoneSimulator/Debug/mtouch-cache/libDGActivityIndicatorView.a(DGActivityIndicatorBallClipRotateMultipleAnimation.o)) was built for newer iOS version (10.1) than being linked (9.0)
error MT5209 : Native linking error : warning: object file (.../obj/iPhoneSimulator/Debug/mtouch-cache/libDGActivityIndicatorView.a(DGActivityIndicatorBallGridPulseAnimation.o)) was built for newer iOS version (10.1) than being linked (9.0)

**Comment by jzeferino** [comment]
Hi there. Can you send me a reproducible project with this error? Appreciate.

**Comment by jzeferino** [comment]
Hi there @cfl777 . Can you send me a reproducible project with this error? Appreciate.

**Comment by cfl777** [comment]
@jzeferino I changed my project to run in the interim, but now when I changed things back it no longer gets this issue. Cannot recreate at the moment, its like xamarin only realizes that something is broken when its triggered in some way, for example when I removed firebase as mentioned above. 

To confirm the the "Deployment target" in "info.plist" that you used for this project wasn't 10.1, but 9.0?

**Comment by jzeferino** [comment]
@cfl777 it was build with iOS 9.0.

If you have any way to reproduce this please let me know.

**Comment by cfl777** [comment]
Okay thats good news - that seemed to be what was reported as possible issues for a problem like this. 

I will do - thank you for assisting.

**Comment by jzeferino** [comment]
This is build with 10.0 now. older versions will work but will warn.
